# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventDirectory.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setObjectName("Tabs")
        self.EventDirectTab = QtWidgets.QWidget()
        self.EventDirectTab.setObjectName("EventDirectTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.EventDirectTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.EventTitlelabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.EventTitlelabel.setFont(font)
        self.EventTitlelabel.setObjectName("EventTitlelabel")
        self.gridLayout_2.addWidget(self.EventTitlelabel, 0, 1, 1, 3)
        self.EventNamelabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EventNamelabel.setFont(font)
        self.EventNamelabel.setObjectName("EventNamelabel")
        self.gridLayout_2.addWidget(self.EventNamelabel, 1, 0, 1, 1)
        self.NameTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.NameTextbox.setObjectName("NameTextbox")
        self.gridLayout_2.addWidget(self.NameTextbox, 1, 1, 1, 1)
        self.EventStartlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EventStartlabel.setFont(font)
        self.EventStartlabel.setObjectName("EventStartlabel")
        self.gridLayout_2.addWidget(self.EventStartlabel, 1, 3, 1, 1)
        self.EventDescriptionlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EventDescriptionlabel.setFont(font)
        self.EventDescriptionlabel.setObjectName("EventDescriptionlabel")
        self.gridLayout_2.addWidget(self.EventDescriptionlabel, 2, 0, 1, 1)
        self.DescriptionTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.DescriptionTextbox.setObjectName("DescriptionTextbox")
        self.gridLayout_2.addWidget(self.DescriptionTextbox, 2, 1, 1, 1)
        self.EventEndlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EventEndlabel.setFont(font)
        self.EventEndlabel.setObjectName("EventEndlabel")
        self.gridLayout_2.addWidget(self.EventEndlabel, 2, 3, 1, 1)
        self.EventEndTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.EventEndTextbox.setObjectName("EventEndTextbox")
        self.gridLayout_2.addWidget(self.EventEndTextbox, 2, 4, 1, 1)
        self.DirectoryTitle = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.DirectoryTitle.setFont(font)
        self.DirectoryTitle.setObjectName("DirectoryTitle")
        self.gridLayout_2.addWidget(self.DirectoryTitle, 3, 1, 1, 3)
        self.SaveEventBut = QtWidgets.QPushButton(self.EventDirectTab)
        self.SaveEventBut.setObjectName("SaveEventBut")
        self.gridLayout_2.addWidget(self.SaveEventBut, 3, 4, 1, 2)
        self.RootDirectlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RootDirectlabel.setFont(font)
        self.RootDirectlabel.setObjectName("RootDirectlabel")
        self.gridLayout_2.addWidget(self.RootDirectlabel, 4, 0, 1, 1)
        self.RootDirectTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.RootDirectTextbox.setObjectName("RootDirectTextbox")
        self.gridLayout_2.addWidget(self.RootDirectTextbox, 4, 1, 1, 1)
        self.RootdirectBut = QtWidgets.QPushButton(self.EventDirectTab)
        self.RootdirectBut.setObjectName("RootdirectBut")
        self.gridLayout_2.addWidget(self.RootdirectBut, 4, 2, 1, 1)
        self.BlueTeamlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BlueTeamlabel.setFont(font)
        self.BlueTeamlabel.setObjectName("BlueTeamlabel")
        self.gridLayout_2.addWidget(self.BlueTeamlabel, 4, 3, 1, 1)
        self.BlueTeamTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.BlueTeamTextbox.setObjectName("BlueTeamTextbox")
        self.gridLayout_2.addWidget(self.BlueTeamTextbox, 4, 4, 1, 1)
        self.BluedirectBut = QtWidgets.QPushButton(self.EventDirectTab)
        self.BluedirectBut.setObjectName("BluedirectBut")
        self.gridLayout_2.addWidget(self.BluedirectBut, 4, 5, 1, 1)
        self.RedTeamlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RedTeamlabel.setFont(font)
        self.RedTeamlabel.setObjectName("RedTeamlabel")
        self.gridLayout_2.addWidget(self.RedTeamlabel, 5, 0, 1, 1)
        self.RedTeamtextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.RedTeamtextbox.setObjectName("RedTeamtextbox")
        self.gridLayout_2.addWidget(self.RedTeamtextbox, 5, 1, 1, 1)
        self.ReddirectBut = QtWidgets.QPushButton(self.EventDirectTab)
        self.ReddirectBut.setObjectName("ReddirectBut")
        self.gridLayout_2.addWidget(self.ReddirectBut, 5, 2, 1, 1)
        self.WhiteTeamLabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.WhiteTeamLabel.setFont(font)
        self.WhiteTeamLabel.setObjectName("WhiteTeamLabel")
        self.gridLayout_2.addWidget(self.WhiteTeamLabel, 5, 3, 1, 1)
        self.whiteTeamTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.whiteTeamTextbox.setObjectName("whiteTeamTextbox")
        self.gridLayout_2.addWidget(self.whiteTeamTextbox, 5, 4, 1, 1)
        self.WhitedirectBut = QtWidgets.QPushButton(self.EventDirectTab)
        self.WhitedirectBut.setObjectName("WhitedirectBut")
        self.gridLayout_2.addWidget(self.WhitedirectBut, 5, 5, 1, 1)
        self.SaveEventBut_2 = QtWidgets.QPushButton(self.EventDirectTab)
        self.SaveEventBut_2.setObjectName("SaveEventBut_2")
        self.gridLayout_2.addWidget(self.SaveEventBut_2, 6, 4, 1, 2)
        self.EventStartTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.EventStartTextbox.setObjectName("EventStartTextbox")
        self.gridLayout_2.addWidget(self.EventStartTextbox, 1, 4, 1, 1)
        self.Tabs.addTab(self.EventDirectTab, "")
        self.LogFileConfiguration = QtWidgets.QWidget()
        self.LogFileConfiguration.setObjectName("LogFileConfiguration")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LogFileConfiguration)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.LogFileConfiguration)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.LogFileConfiguration)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.LogFileConfiguration)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.LogFileConfiguration)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.LogFileConfiguration)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(7)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.tableWidget_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.LogFileConfiguration)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.LogFileConfiguration)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.Tabs.addTab(self.LogFileConfiguration, "")
        self.LogEntryConfiguration = QtWidgets.QWidget()
        self.LogEntryConfiguration.setAccessibleName("")
        self.LogEntryConfiguration.setProperty("page", "")
        self.LogEntryConfiguration.setObjectName("LogEntryConfiguration")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LogEntryConfiguration)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.LogEntryConfiguration)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton_6 = QtWidgets.QPushButton(self.LogEntryConfiguration)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.tableWidget = QtWidgets.QTableWidget(self.LogEntryConfiguration)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setMinimumSectionSize(40)
        self.verticalLayout.addWidget(self.tableWidget)
        self.Tabs.addTab(self.LogEntryConfiguration, "")
        self.VectorConfiguration = QtWidgets.QWidget()
        self.VectorConfiguration.setObjectName("VectorConfiguration")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.VectorConfiguration)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.VectorConfiguration)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.VectorConfiguration)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.VectorConfiguration)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.VectorConfiguration)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.VectorConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tableWidget_4.sizePolicy().hasHeightForWidth())
        self.tableWidget_4.setSizePolicy(sizePolicy)
        self.tableWidget_4.setTabletTracking(False)
        self.tableWidget_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_4.setWordWrap(True)
        self.tableWidget_4.setColumnCount(3)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_4.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_4.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget_4.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.tableWidget_4)
        self.Tabs.addTab(self.VectorConfiguration, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.Tabs.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_5.setMinimumSize(QtCore.QSize(1028, 422))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setMouseTracking(True)
        self.tableWidget_5.setTabletTracking(True)
        self.tableWidget_5.setAutoFillBackground(False)
        self.tableWidget_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_5.setWordWrap(True)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(11)
        self.tableWidget_5.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(10, 0, item)
        self.tableWidget_5.horizontalHeader().setVisible(False)
        self.tableWidget_5.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_5.horizontalHeader().setHighlightSections(False)
        self.tableWidget_5.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget_5.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_5.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_5.verticalHeader().setVisible(False)
        self.tableWidget_5.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_5.verticalHeader().setHighlightSections(False)
        self.verticalLayout_4.addWidget(self.tableWidget_5)
        self.Tabs.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.Tabs.addTab(self.tab_9, "")
        self.gridLayout.addWidget(self.Tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.Export = QtWidgets.QMenu(self.menuFile)
        self.Export.setObjectName("Export")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Save = QtWidgets.QAction(MainWindow)
        self.Save.setObjectName("Save")
        self.actionJPEG = QtWidgets.QAction(MainWindow)
        self.actionJPEG.setObjectName("actionJPEG")
        self.actionPNG = QtWidgets.QAction(MainWindow)
        self.actionPNG.setObjectName("actionPNG")
        self.actionView_Vector = QtWidgets.QAction(MainWindow)
        self.actionView_Vector.setObjectName("actionView_Vector")
        self.actionView_Table = QtWidgets.QAction(MainWindow)
        self.actionView_Table.setObjectName("actionView_Table")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.Export.addAction(self.actionJPEG)
        self.Export.addAction(self.actionPNG)
        self.menuFile.addAction(self.Save)
        self.menuFile.addAction(self.Export.menuAction())
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuView.addAction(self.actionView_Vector)
        self.menuView.addAction(self.actionView_Table)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tabs.setToolTip(_translate("MainWindow", "<html><head/><body><p>dvfas</p></body></html>"))
        self.EventTitlelabel.setText(_translate("MainWindow", "Event Configuration"))
        self.EventNamelabel.setText(_translate("MainWindow", "Event Name"))
        self.EventStartlabel.setText(_translate("MainWindow", "Event Start timestamp"))
        self.EventDescriptionlabel.setText(_translate("MainWindow", "Event Description"))
        self.EventEndlabel.setText(_translate("MainWindow", "Event End timestamp"))
        self.DirectoryTitle.setText(_translate("MainWindow", "Directory Configuration"))
        self.SaveEventBut.setText(_translate("MainWindow", "Save Event"))
        self.RootDirectlabel.setText(_translate("MainWindow", "Root Directory"))
        self.RootdirectBut.setText(_translate("MainWindow", "...."))
        self.BlueTeamlabel.setText(_translate("MainWindow", "Blue Team Folder"))
        self.BluedirectBut.setText(_translate("MainWindow", "...."))
        self.RedTeamlabel.setText(_translate("MainWindow", "Red Team Folder"))
        self.ReddirectBut.setText(_translate("MainWindow", "...."))
        self.WhiteTeamLabel.setText(_translate("MainWindow", "White Team Folder"))
        self.WhitedirectBut.setText(_translate("MainWindow", "...."))
        self.SaveEventBut_2.setText(_translate("MainWindow", "Start Data Ingestion"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.EventDirectTab), _translate("MainWindow", "Event/Directory Config"))
        self.label_2.setText(_translate("MainWindow", "Log File Configuration"))
        self.label_4.setText(_translate("MainWindow", "File Name: "))
        self.label_3.setText(_translate("MainWindow", "Name of Selected Log File"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cleansing Status"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cleansing Status"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Validation Status"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ingestion Status"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))
        self.pushButton.setText(_translate("MainWindow", "Validate"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.LogFileConfiguration), _translate("MainWindow", "Log File Config"))
        self.label.setText(_translate("MainWindow", "Log Entry Configuration"))
        self.pushButton_6.setText(_translate("MainWindow", "Filter"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "List Number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Log Entry Timestamp"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Log Entry Event"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Vector"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.LogEntryConfiguration), _translate("MainWindow", "Log Entry Config"))
        self.label_5.setText(_translate("MainWindow", "Vector Configuration"))
        self.pushButton_3.setText(_translate("MainWindow", "Add Vector"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete Vector"))
        self.pushButton_5.setText(_translate("MainWindow", "Edit Vector"))
        self.tableWidget_4.setSortingEnabled(True)
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Selected"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vector Name"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Vector Description"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.VectorConfiguration), _translate("MainWindow", "Vector Config"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_7), _translate("MainWindow", "Graph View"))
        self.label_6.setText(_translate("MainWindow", "Nodes Configuration in tabular format"))
        self.tableWidget_5.setSortingEnabled(True)
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node Property Visibility"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node ID"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Node Name"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Node Timestamp"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Node Description"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Log Creator"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_5.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Event Type"))
        item = self.tableWidget_5.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Icon Type"))
        item = self.tableWidget_5.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Node Visibility"))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_8), _translate("MainWindow", "Table View"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_9), _translate("MainWindow", "Double View"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.Export.setTitle(_translate("MainWindow", "Export"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.actionJPEG.setText(_translate("MainWindow", "JPEG"))
        self.actionPNG.setText(_translate("MainWindow", "PNG"))
        self.actionView_Vector.setText(_translate("MainWindow", "View Vector"))
        self.actionView_Table.setText(_translate("MainWindow", "View Table"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
