# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventDirectory.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QApplication,QWidget, QFormLayout,QCheckBox, QGroupBox, QWidget,QLineEdit,QDialogButtonBox, QLabel, QMainWindow, QAction, qApp, QPushButton, QDialog,QApplication, QCheckBox, QComboBox, QDateTimeEdit,
        QDial, QDialog, QGridLayout, QGroupBox, QHBoxLayout, QLabel, QLineEdit,
        QProgressBar, QPushButton, QRadioButton, QScrollBar, QSizePolicy,
        QSlider, QSpinBox, QStyleFactory, QTableWidget, QTabWidget, QTextEdit,
        QVBoxLayout, QWidget, QStyle, QDialogButtonBox)
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot
class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1399, 961)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setObjectName("Tabs")
        self.EventDirectTab = QtWidgets.QWidget()
        self.EventDirectTab.setObjectName("EventDirectTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.EventDirectTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.EventTitlelabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.EventTitlelabel.setFont(font)
        self.EventTitlelabel.setObjectName("EventTitlelabel")
        self.gridLayout_2.addWidget(self.EventTitlelabel, 0, 1, 1, 3)
        self.EventNamelabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EventNamelabel.setFont(font)
        self.EventNamelabel.setObjectName("EventNamelabel")
        self.gridLayout_2.addWidget(self.EventNamelabel, 1, 0, 1, 1)
        self.NameTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.NameTextbox.setObjectName("NameTextbox")
        self.gridLayout_2.addWidget(self.NameTextbox, 1, 1, 1, 1)
        self.EventStartlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EventStartlabel.setFont(font)
        self.EventStartlabel.setObjectName("EventStartlabel")
        self.gridLayout_2.addWidget(self.EventStartlabel, 1, 3, 1, 1)
        self.EventDescriptionlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EventDescriptionlabel.setFont(font)
        self.EventDescriptionlabel.setObjectName("EventDescriptionlabel")
        self.gridLayout_2.addWidget(self.EventDescriptionlabel, 2, 0, 1, 1)
        self.DescriptionTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.DescriptionTextbox.setObjectName("DescriptionTextbox")
        self.gridLayout_2.addWidget(self.DescriptionTextbox, 2, 1, 1, 1)
        self.EventEndlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EventEndlabel.setFont(font)
        self.EventEndlabel.setObjectName("EventEndlabel")
        self.gridLayout_2.addWidget(self.EventEndlabel, 2, 3, 1, 1)
        self.EventEndTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.EventEndTextbox.setObjectName("EventEndTextbox")
        self.gridLayout_2.addWidget(self.EventEndTextbox, 2, 4, 1, 1)
        self.DirectoryTitle = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.DirectoryTitle.setFont(font)
        self.DirectoryTitle.setObjectName("DirectoryTitle")
        self.gridLayout_2.addWidget(self.DirectoryTitle, 3, 1, 1, 3)
        self.SaveEventBut = QtWidgets.QPushButton(self.EventDirectTab)
        self.SaveEventBut.setObjectName("SaveEventBut")
        self.gridLayout_2.addWidget(self.SaveEventBut, 3, 4, 1, 2)
        self.RootDirectlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RootDirectlabel.setFont(font)
        self.RootDirectlabel.setObjectName("RootDirectlabel")
        self.gridLayout_2.addWidget(self.RootDirectlabel, 4, 0, 1, 1)
        self.RootDirectTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.RootDirectTextbox.setObjectName("RootDirectTextbox")
        self.gridLayout_2.addWidget(self.RootDirectTextbox, 4, 1, 1, 1)
        self.RootdirectBut = QtWidgets.QPushButton(self.EventDirectTab)
        self.RootdirectBut.setObjectName("RootdirectBut")
        self.gridLayout_2.addWidget(self.RootdirectBut, 4, 2, 1, 1)
        self.BlueTeamlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BlueTeamlabel.setFont(font)
        self.BlueTeamlabel.setObjectName("BlueTeamlabel")
        self.gridLayout_2.addWidget(self.BlueTeamlabel, 4, 3, 1, 1)
        self.BlueTeamTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.BlueTeamTextbox.setObjectName("BlueTeamTextbox")
        self.gridLayout_2.addWidget(self.BlueTeamTextbox, 4, 4, 1, 1)
        self.BluedirectBut = QtWidgets.QPushButton(self.EventDirectTab)
        self.BluedirectBut.setObjectName("BluedirectBut")
        self.gridLayout_2.addWidget(self.BluedirectBut, 4, 5, 1, 1)
        self.RedTeamlabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RedTeamlabel.setFont(font)
        self.RedTeamlabel.setObjectName("RedTeamlabel")
        self.gridLayout_2.addWidget(self.RedTeamlabel, 5, 0, 1, 1)
        self.RedTeamtextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.RedTeamtextbox.setObjectName("RedTeamtextbox")
        self.gridLayout_2.addWidget(self.RedTeamtextbox, 5, 1, 1, 1)
        self.ReddirectBut = QtWidgets.QPushButton(self.EventDirectTab)
        self.ReddirectBut.setObjectName("ReddirectBut")
        self.gridLayout_2.addWidget(self.ReddirectBut, 5, 2, 1, 1)
        self.WhiteTeamLabel = QtWidgets.QLabel(self.EventDirectTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.WhiteTeamLabel.setFont(font)
        self.WhiteTeamLabel.setObjectName("WhiteTeamLabel")
        self.gridLayout_2.addWidget(self.WhiteTeamLabel, 5, 3, 1, 1)
        self.whiteTeamTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.whiteTeamTextbox.setObjectName("whiteTeamTextbox")
        self.gridLayout_2.addWidget(self.whiteTeamTextbox, 5, 4, 1, 1)
        self.WhitedirectBut = QtWidgets.QPushButton(self.EventDirectTab)
        self.WhitedirectBut.setObjectName("WhitedirectBut")
        self.gridLayout_2.addWidget(self.WhitedirectBut, 5, 5, 1, 1)
        self.SaveEventBut_2 = QtWidgets.QPushButton(self.EventDirectTab)
        self.SaveEventBut_2.setObjectName("SaveEventBut_2")
        self.gridLayout_2.addWidget(self.SaveEventBut_2, 6, 4, 1, 2)
        self.EventStartTextbox = QtWidgets.QTextBrowser(self.EventDirectTab)
        self.EventStartTextbox.setObjectName("EventStartTextbox")
        self.gridLayout_2.addWidget(self.EventStartTextbox, 1, 4, 1, 1)
        self.Tabs.addTab(self.EventDirectTab, "")
        self.LogFileConfiguration = QtWidgets.QWidget()
        self.LogFileConfiguration.setObjectName("LogFileConfiguration")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LogFileConfiguration)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.LogFileConfiguration)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.scrollArea = QtWidgets.QScrollArea(self.LogFileConfiguration)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1347, 365))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 0, 1034, 241))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(0, 0, 20, 231))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.LogFileConfiguration)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.LogFileConfiguration)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.LogFileConfiguration)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.LogFileConfiguration)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.LogFileConfiguration)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1347, 364))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(20, 0, 1041, 241))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(7)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_2)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(0, 0, 16, 231))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.Tabs.addTab(self.LogFileConfiguration, "")
        self.LogEntryConfiguration = QtWidgets.QWidget()
        self.LogEntryConfiguration.setAccessibleName("")
        self.LogEntryConfiguration.setProperty("page", "")
        self.LogEntryConfiguration.setObjectName("LogEntryConfiguration")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LogEntryConfiguration)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.LogEntryConfiguration)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton_6 = QtWidgets.QPushButton(self.LogEntryConfiguration)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.tableWidget = QtWidgets.QTableWidget(self.LogEntryConfiguration)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setMinimumSectionSize(40)
        self.verticalLayout.addWidget(self.tableWidget)
        self.Tabs.addTab(self.LogEntryConfiguration, "")
        self.VectorConfiguration = QtWidgets.QWidget()
        self.VectorConfiguration.setObjectName("VectorConfiguration")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.VectorConfiguration)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.VectorConfiguration)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.AddVectorBut = QtWidgets.QPushButton(self.VectorConfiguration)
        self.AddVectorBut.setObjectName("AddVectorBut")
        self.horizontalLayout_3.addWidget(self.AddVectorBut)
        self.DeleteVector = QtWidgets.QPushButton(self.VectorConfiguration)
        self.DeleteVector.setObjectName("DeleteVector")
        self.horizontalLayout_3.addWidget(self.DeleteVector)
        self.EditVectorBut = QtWidgets.QPushButton(self.VectorConfiguration)
        self.EditVectorBut.setObjectName("EditVectorBut")
        self.horizontalLayout_3.addWidget(self.EditVectorBut)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.VectorconfTable = QtWidgets.QTableWidget(self.VectorConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.VectorconfTable.sizePolicy().hasHeightForWidth())
        self.VectorconfTable.setSizePolicy(sizePolicy)
        self.VectorconfTable.setTabletTracking(False)
        self.VectorconfTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.VectorconfTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.VectorconfTable.setWordWrap(True)
        self.VectorconfTable.setColumnCount(3)
        self.VectorconfTable.setObjectName("VectorconfTable")
        self.VectorconfTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.VectorconfTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorconfTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VectorconfTable.setHorizontalHeaderItem(2, item)
        self.VectorconfTable.horizontalHeader().setCascadingSectionResizes(True)
        self.VectorconfTable.horizontalHeader().setDefaultSectionSize(150)
        self.VectorconfTable.horizontalHeader().setMinimumSectionSize(50)
        self.VectorconfTable.horizontalHeader().setStretchLastSection(True)
        self.VectorconfTable.verticalHeader().setSortIndicatorShown(True)
        self.VectorconfTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.VectorconfTable)
        self.Tabs.addTab(self.VectorConfiguration, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 2, 0, 1, 1)
        self.tableWidget_10 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_10.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tableWidget_10.setFont(font)
        self.tableWidget_10.setMouseTracking(True)
        self.tableWidget_10.setTabletTracking(True)
        self.tableWidget_10.setAutoFillBackground(False)
        self.tableWidget_10.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_10.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_10.setWordWrap(True)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(8)
        self.tableWidget_10.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_10.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_10.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_10.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_10.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_10.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_10.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_10.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_10.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_10.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_10.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_10.setItem(10, 0, item)
        self.tableWidget_10.horizontalHeader().setVisible(False)
        self.tableWidget_10.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_10.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_10.horizontalHeader().setHighlightSections(False)
        self.tableWidget_10.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget_10.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_10.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_10.verticalHeader().setVisible(False)
        self.tableWidget_10.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_10.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.tableWidget_10, 6, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_9.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tableWidget_9.setFont(font)
        self.tableWidget_9.setMouseTracking(True)
        self.tableWidget_9.setTabletTracking(True)
        self.tableWidget_9.setAutoFillBackground(False)
        self.tableWidget_9.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget_9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_9.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_9.setWordWrap(True)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(4)
        self.tableWidget_9.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_9.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_9.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_9.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_9.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_9.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_9.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_9.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_9.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_9.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_9.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_9.setItem(10, 0, item)
        self.tableWidget_9.horizontalHeader().setVisible(False)
        self.tableWidget_9.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_9.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_9.horizontalHeader().setHighlightSections(False)
        self.tableWidget_9.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget_9.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_9.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_9.verticalHeader().setVisible(False)
        self.tableWidget_9.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_9.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.tableWidget_9, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 2, 1, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_8.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tableWidget_8.setFont(font)
        self.tableWidget_8.setMouseTracking(True)
        self.tableWidget_8.setTabletTracking(True)
        self.tableWidget_8.setAutoFillBackground(False)
        self.tableWidget_8.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_8.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_8.setWordWrap(True)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(4)
        self.tableWidget_8.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_8.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_8.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_8.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_8.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_8.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_8.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_8.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_8.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_8.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_8.setItem(10, 0, item)
        self.tableWidget_8.horizontalHeader().setVisible(False)
        self.tableWidget_8.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_8.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_8.horizontalHeader().setHighlightSections(False)
        self.tableWidget_8.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget_8.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_8.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_8.verticalHeader().setVisible(False)
        self.tableWidget_8.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_8.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.tableWidget_8, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.Tabs.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_7.sizePolicy().hasHeightForWidth())
        self.tableWidget_7.setSizePolicy(sizePolicy)
        self.tableWidget_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tableWidget_7.setFont(font)
        self.tableWidget_7.setMouseTracking(True)
        self.tableWidget_7.setTabletTracking(True)
        self.tableWidget_7.setAutoFillBackground(False)
        self.tableWidget_7.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_7.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_7.setWordWrap(True)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(5)
        self.tableWidget_7.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_7.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_7.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_7.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_7.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_7.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_7.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_7.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_7.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_7.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_7.setItem(10, 0, item)
        self.tableWidget_7.horizontalHeader().setVisible(False)
        self.tableWidget_7.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_7.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget_7.horizontalHeader().setHighlightSections(False)
        self.tableWidget_7.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget_7.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_7.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_7.verticalHeader().setVisible(False)
        self.tableWidget_7.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_7.verticalHeader().setHighlightSections(False)
        self.verticalLayout_5.addWidget(self.tableWidget_7)
        self.Tabs.addTab(self.tab, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.EventTitlelabel_2 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.EventTitlelabel_2.setFont(font)
        self.EventTitlelabel_2.setObjectName("EventTitlelabel_2")
        self.gridLayout_3.addWidget(self.EventTitlelabel_2, 0, 2, 1, 4)
        self.EventNamelabel_2 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EventNamelabel_2.setFont(font)
        self.EventNamelabel_2.setObjectName("EventNamelabel_2")
        self.gridLayout_3.addWidget(self.EventNamelabel_2, 1, 0, 1, 3)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 1, 4, 2, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 5, 8, 1)
        self.TimeLine = QtWidgets.QComboBox(self.tab_7)
        self.TimeLine.setObjectName("TimeLine")
        self.TimeLine.addItem("")
        self.TimeLine.addItem("")
        self.gridLayout_3.addWidget(self.TimeLine, 2, 0, 1, 3)
        self.EventNamelabel_3 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EventNamelabel_3.setFont(font)
        self.EventNamelabel_3.setObjectName("EventNamelabel_3")
        self.gridLayout_3.addWidget(self.EventNamelabel_3, 3, 0, 1, 3)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 3, 4, 2, 1)
        self.TimeLine_2 = QtWidgets.QComboBox(self.tab_7)
        self.TimeLine_2.setObjectName("TimeLine_2")
        self.TimeLine_2.addItem("")
        self.TimeLine_2.addItem("")
        self.gridLayout_3.addWidget(self.TimeLine_2, 4, 0, 1, 3)
        self.EventTitlelabel_3 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.EventTitlelabel_3.setFont(font)
        self.EventTitlelabel_3.setObjectName("EventTitlelabel_3")
        self.gridLayout_3.addWidget(self.EventTitlelabel_3, 5, 0, 1, 3)
        self.EventNamelabel_4 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EventNamelabel_4.setFont(font)
        self.EventNamelabel_4.setObjectName("EventNamelabel_4")
        self.gridLayout_3.addWidget(self.EventNamelabel_4, 6, 0, 2, 3)
        self.TimeLine_3 = QtWidgets.QComboBox(self.tab_7)
        self.TimeLine_3.setObjectName("TimeLine_3")
        self.TimeLine_3.addItem("")
        self.TimeLine_3.addItem("")
        self.gridLayout_3.addWidget(self.TimeLine_3, 7, 1, 1, 2)
        self.EventNamelabel_5 = QtWidgets.QLabel(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EventNamelabel_5.setFont(font)
        self.EventNamelabel_5.setObjectName("EventNamelabel_5")
        self.gridLayout_3.addWidget(self.EventNamelabel_5, 8, 0, 1, 2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_7)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 8, 2, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 9, 0, 1, 2)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 9, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 9, 3, 1, 2)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_3.addWidget(self.pushButton_8, 10, 0, 1, 2)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_3.addWidget(self.pushButton_9, 10, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 10, 3, 1, 2)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 5, 4, 1, 1)
        self.Tabs.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_5.setMinimumSize(QtCore.QSize(1028, 422))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setMouseTracking(True)
        self.tableWidget_5.setTabletTracking(True)
        self.tableWidget_5.setAutoFillBackground(False)
        self.tableWidget_5.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_5.setWordWrap(True)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(11)
        self.tableWidget_5.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_5.setItem(10, 0, item)
        self.tableWidget_5.horizontalHeader().setVisible(False)
        self.tableWidget_5.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_5.horizontalHeader().setHighlightSections(False)
        self.tableWidget_5.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget_5.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_5.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_5.verticalHeader().setVisible(False)
        self.tableWidget_5.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_5.verticalHeader().setHighlightSections(False)
        self.verticalLayout_4.addWidget(self.tableWidget_5)
        self.Tabs.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.EventNamelabel_8 = QtWidgets.QLabel(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EventNamelabel_8.sizePolicy().hasHeightForWidth())
        self.EventNamelabel_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EventNamelabel_8.setFont(font)
        self.EventNamelabel_8.setObjectName("EventNamelabel_8")
        self.gridLayout_4.addWidget(self.EventNamelabel_8, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 3, 5, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_4.addWidget(self.pushButton_15, 1, 1, 1, 1)
        self.TimeLine_5 = QtWidgets.QComboBox(self.tab_9)
        self.TimeLine_5.setObjectName("TimeLine_5")
        self.TimeLine_5.addItem("")
        self.TimeLine_5.addItem("")
        self.gridLayout_4.addWidget(self.TimeLine_5, 4, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_4.addWidget(self.pushButton_18, 5, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_4.addWidget(self.pushButton_20, 2, 1, 1, 1)
        self.EventNamelabel_7 = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EventNamelabel_7.setFont(font)
        self.EventNamelabel_7.setObjectName("EventNamelabel_7")
        self.gridLayout_4.addWidget(self.EventNamelabel_7, 3, 0, 1, 1)
        self.EventNamelabel_9 = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EventNamelabel_9.setFont(font)
        self.EventNamelabel_9.setScaledContents(False)
        self.EventNamelabel_9.setObjectName("EventNamelabel_9")
        self.gridLayout_4.addWidget(self.EventNamelabel_9, 8, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_4.addWidget(self.pushButton_19, 10, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_4.addWidget(self.pushButton_13, 3, 1, 1, 1)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_6.setMinimumSize(QtCore.QSize(1028, 422))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tableWidget_6.setFont(font)
        self.tableWidget_6.setMouseTracking(True)
        self.tableWidget_6.setTabletTracking(True)
        self.tableWidget_6.setAutoFillBackground(False)
        self.tableWidget_6.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_6.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_6.setWordWrap(True)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(11)
        self.tableWidget_6.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_6.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_6.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_6.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_6.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_6.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_6.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_6.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_6.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_6.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_6.setItem(10, 0, item)
        self.tableWidget_6.horizontalHeader().setVisible(False)
        self.tableWidget_6.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_6.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_6.horizontalHeader().setHighlightSections(False)
        self.tableWidget_6.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget_6.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_6.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_6.verticalHeader().setVisible(False)
        self.tableWidget_6.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget_6.verticalHeader().setHighlightSections(False)
        self.gridLayout_4.addWidget(self.tableWidget_6, 6, 3, 5, 1)
        self.EventTitlelabel_4 = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.EventTitlelabel_4.setFont(font)
        self.EventTitlelabel_4.setObjectName("EventTitlelabel_4")
        self.gridLayout_4.addWidget(self.EventTitlelabel_4, 5, 0, 1, 1)
        self.TimeLine_6 = QtWidgets.QComboBox(self.tab_9)
        self.TimeLine_6.setObjectName("TimeLine_6")
        self.TimeLine_6.addItem("")
        self.TimeLine_6.addItem("")
        self.gridLayout_4.addWidget(self.TimeLine_6, 7, 0, 1, 1)
        self.TimeLine_4 = QtWidgets.QComboBox(self.tab_9)
        self.TimeLine_4.setObjectName("TimeLine_4")
        self.TimeLine_4.addItem("")
        self.TimeLine_4.addItem("")
        self.gridLayout_4.addWidget(self.TimeLine_4, 1, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_4.addWidget(self.pushButton_16, 11, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_4.addWidget(self.pushButton_21, 4, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_4.addWidget(self.pushButton_14, 10, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.plainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_2.setSizePolicy(sizePolicy)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_4.addWidget(self.plainTextEdit_2, 9, 0, 1, 1)
        self.EventNamelabel_6 = QtWidgets.QLabel(self.tab_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.EventNamelabel_6.setFont(font)
        self.EventNamelabel_6.setObjectName("EventNamelabel_6")
        self.gridLayout_4.addWidget(self.EventNamelabel_6, 0, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_4.addWidget(self.pushButton_17, 11, 0, 1, 1)
        self.Tabs.addTab(self.tab_9, "")
        self.horizontalLayout_4.addWidget(self.Tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1399, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.Export = QtWidgets.QMenu(self.menuFile)
        self.Export.setObjectName("Export")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Save = QtWidgets.QAction(MainWindow)
        self.Save.setObjectName("Save")
        self.actionJPEG = QtWidgets.QAction(MainWindow)
        self.actionJPEG.setObjectName("actionJPEG")
        self.actionPNG = QtWidgets.QAction(MainWindow)
        self.actionPNG.setObjectName("actionPNG")
        self.actionView_Vector = QtWidgets.QAction(MainWindow)
        self.actionView_Vector.setObjectName("actionView_Vector")
        self.actionView_Table = QtWidgets.QAction(MainWindow)
        self.actionView_Table.setObjectName("actionView_Table")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCommit = QtWidgets.QAction(MainWindow)
        self.actionCommit.setObjectName("actionCommit")
        self.actionChange_list = QtWidgets.QAction(MainWindow)
        self.actionChange_list.setObjectName("actionChange_list")
        self.Export.addAction(self.actionJPEG)
        self.Export.addAction(self.actionPNG)
        self.menuFile.addAction(self.Save)
        self.menuFile.addAction(self.Export.menuAction())
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCommit)
        self.menuEdit.addAction(self.actionChange_list)
        self.menuView.addAction(self.actionView_Vector)
        self.menuView.addAction(self.actionView_Table)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tabs.setToolTip(_translate("MainWindow", "<html><head/><body><p>dvfas</p></body></html>"))
        self.EventTitlelabel.setText(_translate("MainWindow", "Event Configuration"))
        self.EventNamelabel.setText(_translate("MainWindow", "Event Name"))
        self.EventStartlabel.setText(_translate("MainWindow", "Event Start timestamp"))
        self.EventDescriptionlabel.setText(_translate("MainWindow", "Event Description"))
        self.EventEndlabel.setText(_translate("MainWindow", "Event End timestamp"))
        self.DirectoryTitle.setText(_translate("MainWindow", "Directory Configuration"))
        self.SaveEventBut.setText(_translate("MainWindow", "Save Event"))
        self.RootDirectlabel.setText(_translate("MainWindow", "Root Directory"))
        self.RootdirectBut.setText(_translate("MainWindow", "...."))
        self.BlueTeamlabel.setText(_translate("MainWindow", "Blue Team Folder"))
        self.BluedirectBut.setText(_translate("MainWindow", "...."))
        self.RedTeamlabel.setText(_translate("MainWindow", "Red Team Folder"))
        self.ReddirectBut.setText(_translate("MainWindow", "...."))
        self.WhiteTeamLabel.setText(_translate("MainWindow", "White Team Folder"))
        self.WhitedirectBut.setText(_translate("MainWindow", "...."))
        self.SaveEventBut_2.setText(_translate("MainWindow", "Start Data Ingestion"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.EventDirectTab), _translate("MainWindow", "Event/Directory Config"))
        self.label_2.setText(_translate("MainWindow", "Log File Configuration"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Selected"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Line number"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Error message"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))
        self.pushButton.setText(_translate("MainWindow", "Validate"))
        self.label_4.setText(_translate("MainWindow", "File Name: "))
        self.label_3.setText(_translate("MainWindow", "Name of Selected Log File"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cleansing Status"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cleansing Status"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Validation Status"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ingestion Status"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.LogFileConfiguration), _translate("MainWindow", "Log File Config"))
        self.label.setText(_translate("MainWindow", "Log Entry Configuration"))
        self.pushButton_6.setText(_translate("MainWindow", "Filter"))
        self.pushButton_6.clicked.connect(self.filterButt)
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "List Number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Log Entry Timestamp"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Log Entry Event"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Vector"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.LogEntryConfiguration), _translate("MainWindow", "Log Entry Config"))
        self.label_5.setText(_translate("MainWindow", "Vector Configuration"))
        self.AddVectorBut.setText(_translate("MainWindow", "Add Vector"))
        self.DeleteVector.setText(_translate("MainWindow", "Delete Vector"))
        self.EditVectorBut.setText(_translate("MainWindow", "Edit Vector"))
        self.VectorconfTable.setSortingEnabled(True)
        item = self.VectorconfTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Selected"))
        item = self.VectorconfTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vector Name"))
        item = self.VectorconfTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Vector Description"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.VectorConfiguration), _translate("MainWindow", "Vector Config"))
        self.pushButton_22.setText(_translate("MainWindow", "Pull"))
        self.tableWidget_10.setSortingEnabled(True)
        item = self.tableWidget_10.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_10.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source IP"))
        item = self.tableWidget_10.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Request Timestamp"))
        item = self.tableWidget_10.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_10.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_10.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_10.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Graph"))
        item = self.tableWidget_10.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sync Status"))
        __sortingEnabled = self.tableWidget_10.isSortingEnabled()
        self.tableWidget_10.setSortingEnabled(False)
        self.tableWidget_10.setSortingEnabled(__sortingEnabled)
        self.label_12.setText(_translate("MainWindow", "Approval Sync"))
        self.tableWidget_9.setSortingEnabled(True)
        item = self.tableWidget_9.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vector"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_9.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Graph"))
        __sortingEnabled = self.tableWidget_9.isSortingEnabled()
        self.tableWidget_9.setSortingEnabled(False)
        self.tableWidget_9.setSortingEnabled(__sortingEnabled)
        self.label_11.setText(_translate("MainWindow", "Pushed Vector DB Table"))
        self.pushButton_23.setText(_translate("MainWindow", "Push"))
        self.pushButton_24.setText(_translate("MainWindow", "Commit"))
        self.label_10.setText(_translate("MainWindow", "Pulled Vector DB Table"))
        self.tableWidget_8.setSortingEnabled(True)
        item = self.tableWidget_8.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vector"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_8.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Graph"))
        __sortingEnabled = self.tableWidget_8.isSortingEnabled()
        self.tableWidget_8.setSortingEnabled(False)
        self.tableWidget_8.setSortingEnabled(__sortingEnabled)
        self.label_13.setText(_translate("MainWindow", "Connection Status to Leaad: "))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("MainWindow", "Vector DB"))
        self.label_9.setText(_translate("MainWindow", "Relationship Configuration"))
        self.tableWidget_7.setSortingEnabled(True)
        item = self.tableWidget_7.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Relationship ID"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Parent"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Child"))
        item = self.tableWidget_7.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Label"))
        __sortingEnabled = self.tableWidget_7.isSortingEnabled()
        self.tableWidget_7.setSortingEnabled(False)
        self.tableWidget_7.setSortingEnabled(__sortingEnabled)
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("MainWindow", "Relation Config"))
        self.EventTitlelabel_2.setText(_translate("MainWindow", "Nodes configuration in graphical format"))
        self.EventNamelabel_2.setText(_translate("MainWindow", "TimeLine Orientation"))
        self.pushButton_3.setText(_translate("MainWindow", "Zoom In"))
        self.TimeLine.setItemText(0, _translate("MainWindow", "Option1"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"PICK GUI\graph.png\"/></p></body></html>"))
        self.TimeLine.setItemText(1, _translate("MainWindow", "Option 2"))
        self.EventNamelabel_3.setText(_translate("MainWindow", "Interval Units"))
        self.pushButton_4.setText(_translate("MainWindow", "Zoom Out"))
        self.TimeLine_2.setItemText(0, _translate("MainWindow", "Option1"))
        self.TimeLine_2.setItemText(1, _translate("MainWindow", "Option 2"))
        self.EventTitlelabel_3.setText(_translate("MainWindow", "Graph Configuration"))
        self.EventNamelabel_4.setText(_translate("MainWindow", "Vector"))
        self.TimeLine_3.setItemText(0, _translate("MainWindow", "Option1"))
        self.TimeLine_3.setItemText(1, _translate("MainWindow", "Option 2"))
        self.EventNamelabel_5.setText(_translate("MainWindow", "Description"))
        self.pushButton_5.setText(_translate("MainWindow", "Add Node"))
        self.pushButton_7.setText(_translate("MainWindow", "Add Relationship"))
        self.pushButton_10.setText(_translate("MainWindow", "Edit node"))
        self.pushButton_8.setText(_translate("MainWindow", "Delete Node"))
        self.pushButton_9.setText(_translate("MainWindow", "Remove Relationship"))
        self.pushButton_11.setText(_translate("MainWindow", "Edit Relationship"))
        self.pushButton_12.setText(_translate("MainWindow", "Icon Config"))
        self.pushButton_12.clicked.connect(self.iconButt)
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_7), _translate("MainWindow", "Graph View"))
        self.label_6.setText(_translate("MainWindow", "Nodes Configuration in tabular format"))
        self.tableWidget_5.setSortingEnabled(True)
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node Property Visibility"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node ID"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Node Name"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Node Timestamp"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Node Description"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Log Creator"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_5.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Event Type"))
        item = self.tableWidget_5.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Icon Type"))
        item = self.tableWidget_5.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Node Visibility"))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_8), _translate("MainWindow", "Table View"))
        self.EventNamelabel_8.setText(_translate("MainWindow", "Vector"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"PICK GUI\graph.png\"/></p></body></html>"))
        self.pushButton_15.setText(_translate("MainWindow", "Zoom In"))
        self.TimeLine_5.setItemText(0, _translate("MainWindow", "Option1"))
        self.TimeLine_5.setItemText(1, _translate("MainWindow", "Option 2"))
        self.pushButton_18.setText(_translate("MainWindow", "Edit Relationship"))
        self.pushButton_20.setText(_translate("MainWindow", "Zoom Out"))
        self.EventNamelabel_7.setText(_translate("MainWindow", "Interval Units"))
        self.EventNamelabel_9.setText(_translate("MainWindow", "Description"))
        self.pushButton_19.setText(_translate("MainWindow", "Add Relationship"))
        self.pushButton_13.setText(_translate("MainWindow", "Icon Config"))
        self.pushButton_13.clicked.connect(self.iconButt)
        self.tableWidget_6.setSortingEnabled(True)
        item = self.tableWidget_6.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node Property Visibility"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node ID"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Node Name"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Node Timestamp"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Node Description"))
        item = self.tableWidget_6.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Log Creator"))
        item = self.tableWidget_6.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_6.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Event Type"))
        item = self.tableWidget_6.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Icon Type"))
        item = self.tableWidget_6.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Node Visibility"))
        __sortingEnabled = self.tableWidget_6.isSortingEnabled()
        self.tableWidget_6.setSortingEnabled(False)
        self.tableWidget_6.setSortingEnabled(__sortingEnabled)
        self.EventTitlelabel_4.setText(_translate("MainWindow", "Graph Configuration"))
        self.TimeLine_6.setItemText(0, _translate("MainWindow", "Option1"))
        self.TimeLine_6.setItemText(1, _translate("MainWindow", "Option 2"))
        self.TimeLine_4.setItemText(0, _translate("MainWindow", "Option1"))
        self.TimeLine_4.setItemText(1, _translate("MainWindow", "Option 2"))
        self.pushButton_16.setText(_translate("MainWindow", "Remove Relationship"))
        self.pushButton_21.setText(_translate("MainWindow", "Edit node"))
        self.pushButton_14.setText(_translate("MainWindow", "Add Node"))
        self.EventNamelabel_6.setText(_translate("MainWindow", "TimeLine Orientation"))
        self.pushButton_17.setText(_translate("MainWindow", "Delete Node"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_9), _translate("MainWindow", "Double View"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.Export.setTitle(_translate("MainWindow", "Export"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit/Changes"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.actionJPEG.setText(_translate("MainWindow", "JPEG"))
        self.actionPNG.setText(_translate("MainWindow", "PNG"))
        self.actionView_Vector.setText(_translate("MainWindow", "View Vector"))
        self.actionView_Table.setText(_translate("MainWindow", "View Table"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionCommit.setText(_translate("MainWindow", "Commit"))
        self.actionChange_list.setText(_translate("MainWindow", "Change list"))
#import graph_rc


    #Make PopUp window for when user selects Filter option
    def filterButt(self):
        exPopup = filterPopup(self)
        exPopup.show()

    def iconButt(self):
        exPopup = IconConfigDialog(self)
        exPopup.show()


#Icon Configuration Click Dialog
class IconDialog(QDialog):
   def __init__(self, parent):
        super(IconDialog, self).__init__(parent)
        self.setWindowTitle("HELLO!")
        
        QBtn = QDialogButtonBox.Ok | QDialogButtonBox.Cancel
        
        self.buttonBox = QDialogButtonBox(QBtn)
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)

        self.layout = QVBoxLayout()
        self.layout.addWidget(self.buttonBox)
        self.setLayout(self.layout)

#Icon Configuration Dialog Class
class IconConfigDialog(QDialog):

    def clickMethodGrid(self):
        dialog = IconDialog(self)
        dialog.show()
        print(self.sender().text())

    def __init__(self, parent=None):
        super(IconConfigDialog, self).__init__(parent)

        self.originalPalette = QApplication.palette()

        AddButton = QPushButton("Add")
        AddButton.clicked.connect(self.clickMethodGrid)
        self.createTopLeftGroupBox()

        topLayout = QHBoxLayout()
        topLayout.addWidget(AddButton)
        topLayout.addStretch(1)

        mainLayout = QGridLayout()
        mainLayout.addLayout(topLayout, 0, 0, 1, 2)
        mainLayout.addWidget(self.topLeftGroupBox, 1, 0, 1, 2)
        mainLayout.setRowStretch(1, 1)
        mainLayout.setRowStretch(2, 1)
        mainLayout.setColumnStretch(0, 1)
        mainLayout.setColumnStretch(1, 1)
        self.setLayout(mainLayout)

        self.setWindowTitle("Icon Configuration")

    def createTopLeftGroupBox(self):
        self.topLeftGroupBox = QGroupBox("")

        icons = [
            'SP_ArrowBack',
            'SP_ArrowDown',
            'SP_ArrowForward',
            'SP_ArrowLeft',
            'SP_ArrowRight',
            'SP_ArrowUp',
            'SP_BrowserReload',
            'SP_BrowserStop',
            'SP_CommandLink',
            'SP_ComputerIcon',
            'SP_CustomBase',
            'SP_DesktopIcon',
            'SP_DialogApplyButton',
            'SP_DialogCancelButton',
            'SP_DialogCloseButton',
            'SP_DialogDiscardButton',
            'SP_DialogHelpButton',
            'SP_DialogNoButton',
            'SP_DialogOkButton',
            'SP_DialogOpenButton',
            'SP_DialogResetButton',
            'SP_DialogSaveButton',
            'SP_DialogYesButton',
            'SP_DirClosedIcon',
            'SP_DirHomeIcon',
            'SP_DirIcon',
            'SP_DirLinkIcon',
            'SP_DirOpenIcon',
            'SP_DockWidgetCloseButton',
            'SP_DriveCDIcon',
            'SP_DriveDVDIcon',
            'SP_DriveFDIcon',
            'SP_DriveHDIcon',
            'SP_DriveNetIcon',
            'SP_FileDialogBack',
            'SP_FileDialogContentsView',
            'SP_FileDialogDetailedView',
            'SP_FileDialogEnd',
            'SP_FileDialogInfoView',
            'SP_FileDialogListView',
            'SP_FileDialogNewFolder',
            'SP_FileDialogStart',
            'SP_FileDialogToParent',
            ]
        layout1 = QVBoxLayout()
        layout2 = QGridLayout()
        layout1.addLayout(layout2)

        colSize = 4
        count = 0
        for i in icons:
            btn = QPushButton(i)
            btn.setFlat(True)
            self.x = count
            btn.clicked.connect(self.clickMethodGrid)
            btn.setIcon(self.style().standardIcon(getattr(QStyle, i)))
 
            layout2.addWidget(btn, count / colSize, count % colSize)
            count += 1
             
        self.setLayout(layout1)
        
        self.topLeftGroupBox.setLayout(layout1)
        
    
#Class for filter Popup
class filterPopup(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.filterConfiguration = QLabel("Filter Configuration",self)
        self.filterConfiguration.setFont(QtGui.QFont("Roboto",12, QtGui.QFont.Bold))
        
        self.creatorLabel = QLabel("Creator", self)
        self.creatorLabel.setFont(QtGui.QFont("Roboto",12, QtGui.QFont.Bold))
        
        self.eventType = QLabel("Event Type", self)
        self.eventType.setFont(QtGui.QFont("Roboto",12, QtGui.QFont.Bold))
        
        self.keyWordSearch = QLineEdit(self) #Key Word text
        self.redBox = QCheckBox(self)     #Red Check Box
        self.blueBox = QCheckBox(self)    #Blue Check Box
        self.whiteBox = QCheckBox(self)   #White Check Box
        self.redBox2 = QCheckBox(self)     #Red Check Box
        self.blueBox2 = QCheckBox(self)    #Blue Check Box
        self.whiteBox2 = QCheckBox(self)   #White Check Box
        self.startTime = QLineEdit(self)  #Start time text
        self.endTime = QLineEdit(self)    #End Time text
        buttonBox = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel, self)

        self.formGroupBox = QGroupBox("ihjnrsdijn")
        layout = QFormLayout(self)
        layout.addRow(self.filterConfiguration)
        layout.addRow("Keyword Search:", self.keyWordSearch)
        layout.addRow(self.creatorLabel)
        layout.addRow("Red", self.redBox)
        layout.addRow("Blue", self.blueBox)
        layout.addRow("White", self.whiteBox)
        layout.addRow(self.eventType)
        layout.addRow("Red", self.redBox2)
        layout.addRow("Blue", self.blueBox2)
        layout.addRow("White", self.whiteBox2)
        layout.addRow("Start TimeStamp:", self.startTime)
        layout.addRow("End TimeStamp:", self.endTime)
        layout.addWidget(buttonBox)

        buttonBox.accepted.connect(self.accept)
        buttonBox.rejected.connect(self.reject)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
